name: Build-x86_64-Lean-lede
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     -  'lean-lede/x86_64/.config'
  schedule:
        - cron: 10 1 * * 1

jobs:
  X86:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/trevid/My-action/master/lean-lede/prenv.sh)
        
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: coolsnowwolf/lede

    - name: Get_Release_Version
      run: |
        echo "MERLIN_TAG=$(git show-ref --heads --hash=8)" >> $GITHUB_ENV

    - name: Download and Load custom configuration
      run: |
        curl -fsSL https://raw.githubusercontent.com/trevid/My-action/master/lean-lede/x86_64_custom/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/trevid/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;
        
    - name: When Multi-core compile failure will be rollback to Single core compile
      run: |
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j2 || make -j1 V=s
        sudo df -h
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd bin
        zip -r -o -q -9  x86_64-lede-Package.zip . -i *.ipk
        mkdir /tmp/images
        mv x86_64-lede-Package.zip "/tmp/images/"
        

    
    - name: zipAndMoveFiles
      if: success()
      run: |
        cd bin/targets/
        zip -r -o -q -9 x86_64-lede.zip .
        mv  x86_64-lede.zip "/tmp/images/"

    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: x86_64-lede
        path: /tmp/images/
       
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        artifacts: "/tmp/images/*.*"
        allowUpdates: true 
        commit: master 
        tag: x86_64-lede_${{ env.MERLIN_TAG }}
        body: |
          this is only a latest build from mainline
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false

        
