name: Build-Lean-lede
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     -  'lean-lede/x86_64/.config'
  schedule:
        - cron: 0 */6 * * *

jobs:
  
  MT7621:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/trevid/My-action/master/lean-lede/prenv.sh)
        
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        curl -fsSL https://raw.githubusercontent.com/trevid/My-action/master/lean-lede/mt7621/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/trevid/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;
        
    - name: When Multi-core compile failure will be rollback to Single core compile
      run: |
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j2 || make -j1 V=s
        sudo df -h
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd bin
        zip -r -o -q -9  mt7621-Package.zip . -i *.ipk
        move mt7621-Package.zip "/opt/images/"
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: mt7621
        path: lede/bin/targets/*/*
    
    - name: zipAndMoveFiles
      if: success()
      run: |
        cd bin/targets/*/*
        zip -r -o -q -9 mt7621.zip . -i *.bin
        move mt7621.zip "/opt/images/"
       
    - name: Create Release
    id: create_release
    uses: ncipollo/release-action@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    with:
      artifacts: "/opt/images/*.*"
      allowUpdates: true 
      commit: master 
      tag: mt7621_test
      body: |
        this is only a latest build from mainline
      token: ${{ secrets.GITHUB_TOKEN }}
      draft: false
      prerelease: false

        